stages:
    - build
    - security
    - deploy

# for a simple node.js build, this step is (almost) meaningless
build_app:
    image: node:10.9.0
    stage: build
    script: 
        - npm install
    cache:
        paths:
            - node_modules/
    artifacts:
        paths:
            - node_modules/
                    
dockerize:
    image: docker:stable
    stage: deploy
    variables:
    #     DOCKER_HOST: tcp://docker:2375
        DOCKER_DRIVER: overlay2
        REPOSITORY_URL: $REPO_URL
    services:
        # docker:19.03+ has TLS on by default, see https://gitlab.com/gitlab-org/gitlab-runner/issues/4501#workaround
        - docker:18.09-dind
    before_script:
        - apk add --update python3
        - pip3 install awscli
    script:
        - $(aws ecr get-login --no-include-email --region us-east-2)
        - docker build -t nodegoat:$CI_PIPELINE_ID .
        - docker tag nodegoat:$CI_PIPELINE_ID $REPOSITORY_URL:nodegoat-latest
        - docker tag nodegoat:$CI_PIPELINE_ID $REPOSITORY_URL:nodegoat-$CI_PIPELINE_ID
        - docker push $REPOSITORY_URL:nodegoat-latest
        - docker push $REPOSITORY_URL:nodegoat-$CI_PIPELINE_ID
    after_script:
        - docker images
