# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo/nodegoat

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install
      
#      - run: pwd
#      - run: ls -l

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test
      
      # keep the files around for the scan job
      - persist_to_workspace:
          root: ..
          paths:
            - nodegoat
      
  # job to upload to Veracode for scanning
  veracode_scan:
    docker:
      - image: circleci/openjdk:11.0.2-jdk
      
    working_directory: ~/repo
    
    steps:
      # get the files from the previous job
      - attach_workspace:
          at: .
          
      # 'package' for uploading to Veracode
      - run: 
          name: "Package for upload to Veracode"
          command: |
            #ls -l           
            #ls -al nodegoat
            zip -r upload.zip nodegoat
            #ls -l
      
      # grab the Veracode agent
      - run:
          name: "Get the Veracode agent"
          command: |
            wget https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/19.2.5.6/vosp-api-wrappers-java-19.2.5.6.jar -O VeracodeJavaAPI.jar
            #chmod 755 VeracodeJavaAPI.jar

      # upload for scanning
      - run:
          name: "Upload to Veracode"
          command: java -jar VeracodeJavaAPI.jar 
              -vid $VERACODE_API_ID 
              -vkey $VERACODE_API_KEY 
              -action uploadandscan 
              -appname $VERACODE_APP_NAME 
              -createprofile false 
              -version CircleCI-$CIRCLE_BUILD_NUM 
              -filepath upload.zip
      
workflows:
  version: 2
  build_and_scan:
    jobs:
      - build
      - veracode_scan:
          requires:
            - build


